WITH
reported AS (
    SELECT POSITION_HKEY, VERSION_NUMBER, EFFECTIVITY_DATE, EXTRACTION_PERIOD_END, ACCOUNT_ALIAS, SECURITY_SYMBOL
        , CASE 
            WHEN VERSION_NUMBER = 1 THEN EXTRACTION_PERIOD_END
            ELSE EFFECTIVITY_DATE
        END as VALIDITY_DATE
    FROM {{ ref('REFH_IB_POSITIONS_REPORTED') }}
)

, calculated AS (
    SELECT POSITION_HKEY, VALID_FROM, VALID_TO
    FROM {{ ref('VER_IB_POSITIONS_CALCULATED') }}    
)

SELECT
    r.POSITION_HKEY,
    r.ACCOUNT_ALIAS,
    r.SECURITY_SYMBOL,
    r.VERSION_NUMBER,
    r.EFFECTIVITY_DATE,
    r.EXTRACTION_PERIOD_END,
    r.VALIDITY_DATE

FROM reported r
LEFT JOIN calculated c
    ON r.POSITION_HKEY = c.POSITION_HKEY
    AND r.VALIDITY_DATE BETWEEN c.VALID_FROM AND c.VALID_TO

WHERE c.POSITION_HKEY IS NULL
order by ACCOUNT_ALIAS, SECURITY_SYMBOL
