/** 
 * This file contains the code generated by running the get_IB_ingestion_setup_sql() macro.
 *
 * You can inspect the generated code by placing "{{ get_IB_ingestion_setup_sql() }}"
 * in an empty dbt model and compiling the model (click the compile button in dbt cloud).
 * 
 * To actually execute the code  you need to execute the runner macro run_IB_ingestion_setup()
 * You can do that with the command `dbt run-operation run_IB_ingestion_setup`.
 * This will call the sql generation macro to produce the SQL and then execute it.
 * 
 */

 -- 1. Creation of the schema for the Landing Tables
CREATE SCHEMA IF NOT EXISTS STONKS_DEV.LAND_IB
COMMENT = 'Landing table schema for CSV files from Interactive Brokers.';

-- 2. Creation of the File Format to read the files for the Landing Tables
CREATE FILE FORMAT IF NOT EXISTS STONKS_DEV.LAND_IB.IB_CSV__FF
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    FIELD_OPTIONALLY_ENCLOSED_BY = '\042'
    COMPRESSION = 'AUTO'
    ERROR_ON_COLUMN_COUNT_MISMATCH = True
    EMPTY_FIELD_AS_NULL = True
    NULL_IF = ('', '\\N')
;


-- 3. Creation of the Stage holding the files for the Landing Tables
CREATE STAGE IF NOT EXISTS STONKS_DEV.LAND_IB.IB_CSV__STAGE
        FILE_FORMAT = STONKS_DEV.LAND_IB.IB_CSV__FF
        DIRECTORY = ( ENABLE = true )
        COMMENT = 'Stage for CSV files from Interactive Brokers.'
;
