/**
 * This file contains the SQL generated by compiling the create_dbt_executor_user(...) macro.
 *
 * The code to compile is:
{#
    {%- set prj_name = var('project_short_name') -%}
    {% set useradmin_role = var('useradmin_role') %}

    {{ sf_project_admin.create_dbt_executor_user( 
            prj_name, 
            get_STONKS_user_dictionary().dbt_executor, 
            useradmin_role
    ) }}
#}
*/

    /** CREATE dbt Executor User */ 

    USE ROLE USERADMIN;

    CREATE USER IF NOT EXISTS "STONKS_DBT_EXECUTOR" 
        COMMENT = 'User created by a DBT project'
        PASSWORD = 'Ch4ng3.M3'
        MUST_CHANGE_PASSWORD = TRUE 
        DEFAULT_ROLE = 'STONKS_DBT_EXECUTOR_ROLE'
        DEFAULT_WAREHOUSE = 'USERADMIN'
        DEFAULT_NAMESPACE = 'STONKS_DEV'
    ;
